In [8]:
import os
import pandas as pd

In [16]:
path_to_link = os.path.expanduser('~/price_data_link')
directory = f'{path_to_link}/dukascopy_live/resampled/1min'
fnames = os.listdir(directory)
fnames

['AUDCAD.csv',
 'AUDCHF.csv',
 'AUDJPY.csv',
 'AUDNZD.csv',
 'AUDUSD.csv',
 'CADCHF.csv',
 'CADJPY.csv',
 'CHFJPY.csv',
 'EURAUD.csv',
 'EURCAD.csv',
 'EURCHF.csv',
 'EURGBP.csv',
 'EURJPY.csv',
 'EURNZD.csv',
 'EURUSD.csv',
 'GBPAUD.csv',
 'GBPCAD.csv',
 'GBPCHF.csv',
 'GBPJPY.csv',
 'GBPNZD.csv',
 'GBPUSD.csv',
 'NZDCAD.csv',
 'NZDCHF.csv',
 'NZDJPY.csv',
 'NZDUSD.csv',
 'USDCAD.csv',
 'USDCHF.csv',
 'USDJPY.csv',
 'XAGUSD.csv',
 'XAUUSD.csv']

In [17]:
df = pd.read_csv(f"{directory}/{fnames[0]}")
df

,date,open,high,low,close,vol,ao,ah,al,ac,av,tv
0,2023-08-01 00:00:00,0.88604,0.88612,0.88599,0.88600,100.650000,0.88627,0.88636,0.88618,0.88620,122.750000,81
1,2023-08-01 00:01:00,0.88600,0.88620,0.88600,0.88610,87.000000,0.88621,0.88640,0.88621,0.88628,91.290000,69
2,2023-08-01 00:02:00,0.88607,0.88621,0.88605,0.88613,70.320000,0.88628,0.88642,0.88625,0.88634,69.720000,58
3,2023-08-01 00:03:00,0.88615,0.88636,0.88614,0.88629,49.200000,0.88635,0.88654,0.88632,0.88647,44.640003,37
4,2023-08-01 00:04:00,0.88630,0.88630,0.88617,0.88619,39.460003,0.88647,0.88649,0.88636,0.88637,36.000000,30
...,...,...,...,...,...,...,...,...,...,...,...,...
553026,2025-01-24 21:55:00,0.90554,0.90574,0.90550,0.90572,219.660000,0.90606,0.90606,0.90588,0.90601,204.720000,100
553027,2025-01-24 21:56:00,0.90560,0.90576,0.90546,0.90550,314.790000,0.90600,0.90604,0.90588,0.90591,309.720000,166
553028,2025-01-24 21:57:00,0.90550,0.90574,0.90548,0.90561,149.520000,0.90591,0.90607,0.90589,0.90602,155.400010,115
553029,2025-01-24 21:58:00,0.90582,0.90582,0.90556,0.90565,88.200005,0.90602,0.90609,0.90598,0.90607,85.500000,70
553030,2025-01-24 21:59:00,0.90565,0.90569,0.90492,0.90492,56.219997,0.90608,0.90666,0.90603,0.90666,56.219997,62

In [12]:
[x for x in os.listdir(path_to_link) if "dukas" in x]

['dukascopy',
 '1m_candle_dukascopy',
 'dukas_bins',
 'dukas_1m_arb',
 'dukascopy_live']